ACP/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ACP.Data;
using ACP.Models;
using System;
using System.Threading.Tasks;
using System.Linq;
using ACP.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using ACP.Services.Interfaces;

[Authorize(Roles = "Administrador,Operario")]
public class ClientesController : Controller
{
    private readonly IServicioCliente _servicioCliente;
    private readonly IServicioVehiculo _servicioVehiculo;

    public ClientesController(
        IServicioCliente servicioCliente, 
        IServicioVehiculo servicioVehiculo
        )
    {
        _servicioCliente = servicioCliente;
        _servicioVehiculo = servicioVehiculo;
    }

    // GET: Clientes
    [HttpGet]
    public async Task<IActionResult> Index() 
    { 
        return View( await _servicioCliente.ObtenerTodosLosClientes() );
    } 
    
    // GET: Clientes/Create
    public IActionResult Create() 
    {
        return View();
    } 
    
    // POST: Clientes/Create
    [HttpPost] 
    [ValidateAntiForgeryToken] 
    public async Task<IActionResult> Create(
        [Bind("Id,Nombre,Apellido,Documento,Telefono,Correo,VehiculosSeleccionados")] CrearClienteViewModel clienteViewModel
        ) 
    {

        if (ModelState.IsValid) 
        {
            var clienteExistente = await _servicioCliente.ExisteCliente(v => v.Documento == clienteViewModel.Documento);


            if (clienteExistente)
            {
                ModelState.AddModelError("Documento", "El documento ingresado ya esta registrado.");

                TempData["ErrorMessage"] = "Documento registrado previamente.";

                return View(clienteViewModel);
            }

            var cliente = new Cliente()
            {
                Id = Guid.NewGuid(),
                Nombre = clienteViewModel.Nombre,
                Apellido = clienteViewModel.Apellido,
                Documento = clienteViewModel.Documento,
                Telefono = clienteViewModel.Telefono,
                Correo = clienteViewModel.Correo
            };

            if(clienteViewModel.VehiculosSeleccionados != null)
            {
                var vehiculos = await _servicioVehiculo
                    .VehiculosFiltrados(v => clienteViewModel.VehiculosSeleccionados.Contains(v.Placa)
                    );

                foreach (var vehiculo in vehiculos)
                {
                    if(!cliente.Vehiculos.Any(v => v.Placa == vehiculo.Placa))
                    {
                        cliente.Vehiculos.Add(vehiculo);

                        if(!vehiculo.Clientes.Any(c => c.Documento == cliente.Documento))
                        {
                            vehiculo.Clientes.Add(cliente);
                        }
                    }
                }
            }

            await _servicioCliente.CrearCliente(cliente); // Guarda cambios

            TempData["SuccessMessage"] = "El cliente se creó correctamente.";

            return RedirectToAction(nameof(Index)); 
        }

        TempData["ErrorMessage"] = "Hubo un error al intentar crear el registro.";

        return View(clienteViewModel); 
    }

    [HttpGet]
    public async Task<IActionResult> Details(Guid id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var cliente = await _servicioCliente.ObtenerPorIdConRelaciones(id);
        
        if (cliente == null) return NotFound();

        var viewModel = new DetailsClienteViewModel
        {
            Id = cliente.Id,
            Nombre = $"{cliente.Nombre} {cliente.Apellido}",
            Email = cliente.Correo,
            Telefono = cliente.Telefono,
            Vehiculos = cliente
                .Vehiculos
                .Select(v => new DetailsClienteViewModel.VehiculoInfo
                {
                    Placa = v.Placa,
                    Color = v.Color.Nombre,
                    Referencia = v.Referencia.Nombre
                })
                .ToList()
        };


        return View(viewModel); 
    }

    [HttpGet]
    public async Task<IActionResult> GetClientesDocumentos(string term)
    {
        var documentos = await _servicioCliente.FiltrarYMapear<string>(
            v => v.Documento.Contains(term),
            v => v.Documento
            );

        return Json(documentos);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Guid id)
    {
        var resultado = await _servicioCliente.Eliminar(id);

        if (resultado)
        {
            return Json(new { success = true, message = "Registro eliminado correctamente." });
        }
        
        return Json(new { success = false, message = "No se pudo eliminar el registro." });
        
    }
}

ACP/Controllers/UsuariosController.cs
using ACP.Models;
using ACP.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

[Authorize(Roles = "Administrador")]
public class UsuariosController : Controller
{
    private readonly UserManager<ApplicationUser> _userManager;

    public UsuariosController(UserManager<ApplicationUser> userManager)
    {
        _userManager = userManager;
    }

    // GET: Users
    public async Task<IActionResult> Index()
    {
        var users = await _userManager.Users.ToListAsync();

        var nonAdminUsers = new List<ApplicationUser>();

        foreach(var user in users)
        {
            if (!await _userManager.IsInRoleAsync(user, "Administrador"))
            {
                nonAdminUsers.Add(user);
            }
        }

        return View(nonAdminUsers);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(string id)
    {
        var user = await _userManager.FindByIdAsync(id);

        if (user == null) return NotFound();

        var model = new EditarUsuarioViewModel
        {
            Id = user.Id,
            FirstName = user.FirstName,
            LastName = user.LastName,
            PhoneNumber = user.PhoneNumber!,
            Email = user.Email!
        };

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(EditarUsuarioViewModel model)
    {
        if (ModelState.IsValid) { 
            
            var user = await _userManager.FindByIdAsync(model.Id); 
            
            if (user == null) return NotFound(); 
            
            user.Email = model.Email; 
            user.FirstName = model.FirstName; 
            user.LastName = model.LastName; 
            user.PhoneNumber = model.PhoneNumber; 

            var result = await _userManager.UpdateAsync(user); 

            if (result.Succeeded) 
            { 
                return RedirectToAction(nameof(Index)); 
            }
            
            foreach (var error in result.Errors) 
            { 
                ModelState.AddModelError(string.Empty, error.Description); 
            } 
        }

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(string id)
    {
        var user = await _userManager.FindByIdAsync(id); 
        
        if (user == null) return NotFound();
        
        var result = await _userManager.DeleteAsync(user);

        if (result.Succeeded) 
        {
            return Json(new {success = true, message = "Usuario eliminado exitosamente."});
        } 

        return Json(new { success = false, message = "No se pudo el eliminar el Usuario indicado." });
    }

    [HttpGet]
    public async Task<IActionResult> Details(string id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var usuario = await _userManager.FindByIdAsync(id);

        if (usuario == null) return NotFound();

        var viewModel = new DetalleUsuarioViewModel
        {
            Id = usuario.Id,
            FirstName = usuario.FirstName,
            LastName = usuario.LastName,
            PhoneNumber = usuario.PhoneNumber,
            Email = usuario.Email
        };


        return View(viewModel);
    }

}

ACP/Controllers/VehiculosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ACP.Data;
using ACP.Models;
using System;
using System.Threading.Tasks;
using System.Linq;
using ACP.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using ACP.Services.Interfaces;

[Authorize(Roles = "Administrador,Operario")]
public class VehiculosController : Controller
{
    private readonly IServicioVehiculo _servicioVehiculo;
    private readonly IServicioCliente _servicioCliente;
    private readonly IServicioFabricante _servicioFabricante;
    private readonly IServicioColor _servicioColor;
    private readonly IServicioReferencia _servicioReferencia;

    public VehiculosController(
        IServicioVehiculo servicioVehiculo,
        IServicioFabricante servicioFabricante,
        IServicioColor servicioColor,
        IServicioReferencia servicioReferencia,
        IServicioCliente servicioCliente)
    {
        _servicioVehiculo = servicioVehiculo;
        _servicioFabricante = servicioFabricante;
        _servicioColor = servicioColor;
        _servicioReferencia = servicioReferencia;
        _servicioCliente = servicioCliente;
    }

    // GET: Vehiculos
    public async Task<IActionResult> Index()
    {
        var vehiculos = await _servicioVehiculo.ObtenerTodosConRelaciones();

        return View(vehiculos);
    }

    // GET: Vehiculos/Create
    public async Task<IActionResult> Create(string placa = "")
    {
        var viewModel = new CrearVehiculoViewModel
        {
            Placa = placa,
            Fabricantes = GetSelectListWithDefaultOption(
                await _servicioFabricante.Mapear(f => new SelectListItem
                {
                    Value = f.Id.ToString(),
                    Text = f.Nombre
                })),
            Colores = GetSelectListWithDefaultOption(
                 await _servicioColor.Mapear(c => new SelectListItem
                 {
                     Value = c.Id.ToString(),
                     Text = c.Nombre
                 })),
            Referencias = GetSelectListWithDefaultOption(
                 await _servicioReferencia.Mapear(r => new SelectListItem
                 {
                     Value = r.Id.ToString(),
                     Text = r.Nombre
                 })),
            Modelos = GetAnios()
        };

        return View(viewModel);
    }

    // POST: Vehiculos/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(
        [Bind("Placa,Modelo,FabricanteId,ColorId,ClientesSeleccionados,ReferenciaId")] CrearVehiculoViewModel vehiculoViewModel
        )
    {
        if (ModelState.IsValid)
        {
            var vehiculoExistente = await _servicioVehiculo.ExisteVehiculo(v => v.Placa == vehiculoViewModel.Placa);

            if (vehiculoExistente)
            {
                ModelState.AddModelError("Placa", "La placa ingresada ya esta registrada.");
                return View(vehiculoViewModel);
            }

            var vehiculo = new Vehiculo()
            {
                Id = Guid.NewGuid(),
                Placa = vehiculoViewModel.Placa,
                Modelo = vehiculoViewModel.Modelo,
                FabricanteId = vehiculoViewModel.FabricanteId,
                ColorId = vehiculoViewModel.ColorId,
                ReferenciaId = vehiculoViewModel.ReferenciaId
            };

            if (vehiculoViewModel.ClientesSeleccionados != null)
            {
                var clientes = await _servicioCliente.ClientesFiltrados(c => vehiculoViewModel.ClientesSeleccionados.Contains(c.Documento));

                foreach (var cliente in clientes)
                {
                    if (!vehiculo.Clientes.Any(c => c.Documento == cliente.Documento))
                    {
                        vehiculo.Clientes.Add(cliente);

                        if (!cliente.Vehiculos.Any(v => v.Placa == vehiculo.Placa))
                        {
                            cliente.Vehiculos.Add(vehiculo);
                        }
                    }
                }
            }

            await _servicioVehiculo.CrearVehiculo(vehiculo); // Hace guardado del context
            TempData["SuccessMessage"] = "El vehiculo se creó correctamente.";

            return RedirectToAction(nameof(Index));
        }

        vehiculoViewModel.Fabricantes = GetSelectListWithDefaultOption(
            await _servicioFabricante.Mapear(f => new SelectListItem
            {
                Value = f.Id.ToString(),
                Text = f.Nombre
            }));
        vehiculoViewModel.Colores = GetSelectListWithDefaultOption(
            await _servicioColor.Mapear(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Nombre
            }));
        vehiculoViewModel.Referencias = GetSelectListWithDefaultOption(
            await _servicioReferencia.Mapear(r => new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = r.Nombre
            }));
        vehiculoViewModel.Modelos = GetAnios();

        return View(vehiculoViewModel);
    }

    [HttpGet]
    public async Task<IActionResult> GetVehiculoPlacas(string term)
    {
        var placas = await _servicioVehiculo.FiltrarYMapear<string>(
            v => v.Placa.Contains(term),
            v => v.Placa
            );

        return Json(placas);
    }

    [HttpGet]
    public async Task<IActionResult> GetReferenciasByFabricante(Guid fabricanteId)
    {
        var referencias = await _servicioReferencia.FiltrarYMapear<object>(
            r => r.FabricanteId == fabricanteId,
            r => new { r.Id, r.Nombre }
            );

        return Json(referencias);
    }

    [HttpPost]
    public async Task<IActionResult> Delete(Guid id)
    {
        var resultado = await _servicioVehiculo.Eliminar(id);

        if (resultado)
        {
            return Json(new { success = true, message = "Registro eliminado correctamente." });
        }
        
        return Json(new { success = false, message = "No se pudo eliminar el registro." });
        
    }

    // Métodos de ayuda

    private SelectList GetAnios()
    {
        int startYear = 1980; // Puedes cambiar este año inicial según tus necesidades
        int endYear = DateTime.Now.Year + 1; 
        var years = new List<SelectListItem>(); 
        
        for (int year = endYear; year >= startYear; year--) 
        { 
            years.Add(
                new SelectListItem { Value = year.ToString(), Text = year.ToString() }
                ); 
        }

        return new SelectList(years, "Value", "Text");
    }

    private static SelectList GetSelectListWithDefaultOption(
        IEnumerable<SelectListItem> items, 
        string defaultText = "-- selecciona --") 
    { 
        var selectList = new List<SelectListItem> 
        { 
            new SelectListItem { Value = "", Text = defaultText } 
        }; 
        
        selectList.AddRange(items); 
        
        return new SelectList(selectList, "Value", "Text"); 
    }

}

ACP/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ACP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/jquery-ui/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/lib/select2/dist/css/select2.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ACP.styles.css" asp-append-version="true" />
    <style>
        .toast-top-right {
            top: 80px !important; /* Baja las notificaciones 80px de la parte superior */
            right: 20px !important; /* Mantén la posición en la esquina */
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ACP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if(SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   id="clientes"
                                   asp-controller="Clientes"
                                   asp-action="Index">
                                   Clientes
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   id="vehiculos"
                                   asp-controller="Vehiculos"
                                   asp-action="Index">
                                   Vehiculos
                                </a>
                            </li>
                           @if (User.IsInRole("Administrador"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark"
                                       id="register"
                                       asp-controller="Usuarios"
                                       asp-action="Index">
                                       Operarios
                                    </a>
                                </li>
                            }
                        </ul>                        
                    }
                    <partial name="_LoginPartial.cshtml"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ACP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/select2/dist/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>